name: Build single binary on Linux

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - magistra

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: RUST_BACKTRACE=1 bash helper/build.sh
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: cidr-chef
          path: artifacts/cidr-chef
      - name: Inspect disk usage
        shell: bash
        run: du -sh .
